# Generated by Django 3.1 on 2020-08-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_meta', to='projects.projectmeta'),
        ),
    ]
