# Generated by Django 3.1 on 2020-08-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200812_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmeta'),
        ),
    ]
