# Generated by Django 3.1 on 2020-08-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200813_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmeta',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_meta',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.projectmeta'),
        ),
    ]
