# Generated by Django 3.1 on 2020-08-13 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_auto_20200813_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectsmeta', to=settings.AUTH_USER_MODEL),
        ),
    ]
