# Generated by Django 3.1 on 2020-08-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectmeta_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeta',
            name='root_path',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
