# Generated by Django 3.1 on 2020-08-18 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_auto_20200818_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmeta',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projectsmeta', to=settings.AUTH_USER_MODEL),
        ),
    ]
