# Generated by Django 3.1 on 2020-08-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0001_initial'),
        ('projects', '0013_project_datasets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='datasets',
        ),
        migrations.AddField(
            model_name='projectmeta',
            name='datasets',
            field=models.ManyToManyField(default=None, to='datasets.Dataset'),
        ),
    ]
