# Generated by Django 3.1 on 2020-08-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
        ('projects', '0015_auto_20200820_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='processes.process'),
        ),
    ]
