# Generated by Django 3.1.1 on 2020-09-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_auto_20200828_1957'),
        ('projects', '0017_auto_20200828_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[
                 ('R', 'running'), ('D', 'done'), ('F', 'failed')], editable=False, max_length=10)),
                ('output_path', models.CharField(editable=False, max_length=200)),
                ('image_output_path', models.CharField(
                    editable=False, max_length=200)),
                ('csv_output_path', models.CharField(
                    editable=False, max_length=200)),
                ('dataset', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='datasets'
        ),
        migrations.AddField(
            model_name='project',
            name='datasets',
            field=models.ManyToManyField(
                default=None, through='projects.Data', to='datasets.Dataset'),
        ),
    ]
