# Generated by Django 3.1.1 on 2020-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200902_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dataset_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='data',
            name='project_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
