# Generated by Django 3.1.1 on 2020-09-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200905_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='csv_output_path',
            new_name='csv_output_folder',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='image_output_path',
            new_name='image_output_folder',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='output_path',
            new_name='output_folder',
        ),
        migrations.AddField(
            model_name='data',
            name='csv_output_zip_path',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='image_output_zip_path',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
