# Generated by Django 3.1.1 on 2020-09-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_auto_20200910_1618'),
        ('projects', '0021_auto_20200910_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='processes.process'),
        ),
    ]
