# Generated by Django 3.1.1 on 2020-09-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200910_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmeta',
            old_name='time',
            new_name='date',
        ),
    ]
