# Generated by Django 3.1 on 2020-10-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200914_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='dataset_name',
        ),
        migrations.RemoveField(
            model_name='data',
            name='project_name',
        ),
    ]
