# Generated by Django 3.1 on 2020-08-26 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import processes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PyTorchModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('model_type', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('model_filepath', models.FileField(
                    upload_to=processes.models.upload_pytorch_model)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessMeta',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('output_path', models.CharField(editable=False, max_length=200)),
                ('image_output_path', models.CharField(
                    editable=False, max_length=200)),
                ('csv_output_path', models.CharField(
                    editable=False, max_length=200)),
                ('status', models.IntegerField(default=0, editable=False)),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('pytorch_process_model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='procmeta', to='processes.pytorchmodel')),
                ('pytorch_viz_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='vizmeta', to='processes.pytorchmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('process_meta', models.OneToOneField(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='processes.processmeta')),
            ],
        ),
    ]
