# Generated by Django 3.1 on 2020-08-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pytorchmodel',
            old_name='model_filepath',
            new_name='filepath',
        ),
        migrations.RemoveField(
            model_name='processmeta',
            name='pytorch_viz_model',
        ),
        migrations.AddField(
            model_name='processmeta',
            name='viz_tech',
            field=models.CharField(default='', max_length=100),
        ),
    ]
