# Generated by Django 3.1 on 2020-08-28 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0002_auto_20200826_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='owner',
        ),
        migrations.AddField(
            model_name='process',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='processmeta',
            name='owner',
        ),
        migrations.AddField(
            model_name='processmeta',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processesmeta', to=settings.AUTH_USER_MODEL),
        ),
    ]
