# Generated by Django 3.1 on 2020-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20200828_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmeta',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
