# Generated by Django 3.1 on 2020-10-27 01:36

from django.db import migrations, models
import processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_auto_20200910_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('metric_func', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('filepath', models.FileField(upload_to=processes.models.upload_metric_func)),
            ],
        ),
    ]
