# Generated by Django 3.1 on 2020-10-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_processmeta_metric_func'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processmeta',
            old_name='metric_func',
            new_name='metric_funcs',
        ),
    ]
